#!/bin/sh

. "$SOURCE"/tap/libtap.sh
cd "$BUILD"

TMPDIR=$(test_tmpdir)
TESTS_DIR="$SOURCE"/data
ZSCANNER_TOOL="$BUILD"/zscanner-tool

plan_lazy

mkdir "$TMPDIR"/includes/
for a in 1 2 3 4 5 6; do
    cp -a "$TESTS_DIR"/includes/include"$a" "$TMPDIR"/includes/;
done

for case in $(cat "$SOURCE"/zscanner-TESTS); do
    casein=$(test_file_path data/"$case".in)
    caseout=$(test_file_path data/"$case".out)
    filein="$TMPDIR"/"$case".in
    fileout="$TMPDIR"/"$case".out

    sed -e "s|@BUILD@|$BUILD|;s|@SOURCE@|$SOURCE|;" < "$casein" > "$filein"

    "$ZSCANNER_TOOL" -m 2 . "$filein" > "$fileout"

    ZSCANNER_RET=$?

    if [ "$?" -ne 0 ]; then
	ok "$case: zscanner-tool run" false
	skip
    fi
    ok "$case: zscanner-tool" true

    if cmp -s "$fileout" "$caseout"; then
	ok "$case: output matches" true
    else
	ok "$case: output differs" false
	diff -urNap "$caseout" "$fileout" | while read line; do diag "$line"; done
    fi
done
