@node Running Knot DNS, Security Considerations, Knot DNS Configuration, Top
@chapter Running Knot DNS

@menu
* Running a slave server::       
* Running a master server::       
* Controlling running daemon::       
@end menu

@node Running a slave server
@section Running a slave server

@node Running a master server
@section Running a master server

@node Controlling running daemon
@section Controlling running daemon
