#line 2 "cf-lex.c"

#line 4 "cf-lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cf_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cf_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cf_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void cf_restart (FILE *input_file ,yyscan_t yyscanner );
void cf__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void cf__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void cf_pop_buffer_state (yyscan_t yyscanner );

static void cf_ensure_buffer_stack (yyscan_t yyscanner );
static void cf__load_buffer_state (yyscan_t yyscanner );
static void cf__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER cf__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE cf__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *cf_alloc (yy_size_t ,yyscan_t yyscanner );
void *cf_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void cf_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer cf__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cf_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[563] =
    {   0,
        0,    0,    0,    0,   92,   91,    2,    3,   91,   91,
        3,   86,   74,   87,   86,   91,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       88,   91,    2,    0,   85,   84,    0,    1,   86,   86,
       74,    0,   86,   73,   72,   72,    0,   77,    0,    0,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   70,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   88,    0,   90,   89,
       86,    0,   77,   77,   77,    0,    0,   86,   68,   56,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   11,   86,   55,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       51,   86,   86,   86,   86,   89,   86,    0,    0,   77,
       77,   77,    0,    0,    0,    0,   76,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   16,   86,   86,
       86,   86,   86,   86,   63,   86,   86,   12,   86,   86,

       86,    8,   86,   50,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       31,   86,   86,   86,   86,   58,   86,    0,    0,    0,
        0,    0,    0,   86,   53,   86,   86,   86,   86,   62,
       86,   86,   66,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       15,   86,    0,    0,   86,   86,   86,   86,   86,   86,
       86,   14,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   86,   86,   86,   64,   86,   86,   86,   86,   86,
       33,   86,   86,   57,   86,   60,   59,   86,   61,    4,
       86,   86,   86,   86,   86,   86,   23,   86,   86,   75,
        0,    0,   49,   86,   86,   52,   86,   86,   86,   86,
       86,   86,   86,   71,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   32,   86,   86,   13,   86,   86,   86,
       10,   86,   86,   86,    7,   65,   28,   24,   86,    0,
        0,   86,   86,   67,   86,   86,   86,   78,   86,    6,
        5,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   69,

       86,   86,   77,    0,   86,   86,   86,   86,   86,   79,
       86,   86,   86,   86,   86,   86,   54,   86,   86,   86,
       26,   86,   86,   86,   86,   86,   86,   86,   86,   43,
       25,   86,    0,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   48,   86,   86,   86,   86,   86,   86,   86,
       27,   86,   86,   86,   40,   86,   86,   86,   86,   86,
       86,   17,   86,   86,   80,   81,   82,   83,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   22,   86,
       86,   86,   86,   86,   86,   86,   47,   86,   86,   86,

       86,   86,   86,   86,   44,   45,   86,   86,   36,   86,
       86,   86,   86,   86,   86,   86,   86,   35,   86,   21,
       86,   86,   86,   86,   38,   86,   86,   19,   20,   86,
       86,   86,   86,   86,   86,   86,   86,   39,    9,   41,
       42,   18,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   30,   29,   86,   37,   46,   86,   86,
       34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    4,    4,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,    9,   16,    9,   17,   18,    1,
        4,    1,    1,    4,   19,   19,   19,   19,   19,   19,
       20,   21,   21,   21,   21,   21,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,    1,   23,    4,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   21,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,    4,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    1,    5,    2,
        2,    1,    1,    2,    5,    5,    5,    5,    5,    5,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[579] =
    {   0,
        0,    0,   48,   52,  781,  782,   56,  782,   57,  777,
        0,    0,   56,  762,   97,  761,   93,  752,   77,  100,
      735,  742,  733,   81,  103,  744,   23,  747,   36,  102,
      103,  727,  109,  113,  729,  106,  118,  119,  739,  730,
      152,  155,  160,  161,  782,  782,  764,  782,    0,  158,
        0,  749,    0,    0,    0,    0,  748,  166,  747,  746,
      734,  726,  712,  711,  731,  720,  723,  729,  712,  711,
      711,  716,  712,  724,  706,  718,  122,  716,  697,  702,
      712,  695,  698,  707,  709,    0,  710,  696,  707,  692,
      698,  696,  148,  701,  159,  689,  705,  696,  700,  698,

      685,  700,  683,  682,  681,  684,  196,  183,  782,  702,
      711,  701,  709,  191,  213,  699,  221,  674,  676,    0,
      676,  678,  668,  667,  665,  683,  665,  668,  676,  660,
      676,  659,  664,  174,  662,  670,  657,  655,  653,    0,
      688,  661,  665,  662,  648,  649,  660,  650,  659,  661,
      208,  648,  214,  643,  219,  646,  635,  656,  639,  637,
        0,  641,  643,  669,  646,  782,  254,  657,    0,  665,
        0,  262,  655,  663,  270,  292,  782,  641,  623,  641,
      636,  625,  632,  633,  637,  633,  620,    0,  621,  652,
      621,  614,  612,  626,    0,  613,  646,    0,  623,  212,

      184,    0,  618,    0,  602,  642,  605,  614,  609,  620,
      615,  618,  601,  597,  615,  601,  609,  595,  593,  592,
        0,  601,  600,  603,  276,  215,  623,  622,  612,    0,
      620,    0,  306,  585,    0,  594,  584,  586,  596,    0,
      587,  594,    0,  578,  252,  594,  585,  589,  580,  585,
      584,  576,  574,  584,  582,  580,  560,  572,  582,  570,
      575,  562,  559,  566,  559,  556,  557,  554,  565,  564,
      558,  563,  559,  562,  552,  552,  547,  550,  542,  552,
        0,  314,    0,  576,  541,  541,  543,  545,  554,  549,
      570,    0,  548,  543,  538,  530,  543,  542,  545,  171,

      562,  531,  528,  527,    0,  558,  535,  527,  529,  519,
        0,  527,  552,    0,  514,    0,    0,  528,    0,    0,
      527,  519,  547,  516,  521,  509,    0,  507,  514,    0,
      540,    0,    0,  509,  502,    0,  510,  537,  302,  529,
      517,  512,  492,    0,  502,  511,  499,  501,  497,  497,
      526,  525,  299,    0,  493,  494,    0,  502,  489,  486,
        0,  485,  496,  491,    0,    0,    0,    0,  494,    0,
      514,  484,  483,    0,  494,  481,  488,    0,  333,    0,
        0,  473,  486,  478,  480,  475,  504,  483,  470,  471,
      463,  477,  472,  476,  470,  495,  463,  471,  457,    0,

      461,  490,    0,    0,  458,  467,  457,  468,  444,    0,
      247,  475,  480,  447,  481,  451,    0,  316,  451,  460,
        0,  441,  440,  446,  437,  437,  452,  443,  470,    0,
        0,  434,  452,  430,  466,  424,  445,  442,  456,  453,
      454,  455,    0,  437,  431,  438,  434,  432,  427,  411,
        0,  417,  428,  421,  448,  422,  420,  417,  403,  408,
      403,    0,  413,  414,    0,    0,    0,    0,  413,  402,
      407,  408,  403,  412,  405,  406,  400,  408,  394,  406,
      407,  400,  395,  424,  392,  400,  387,  397,    0,  398,
      396,  389,  386,  384,  392,  376,    0,  257,  392,  370,

      387,  389,  373,  373,    0,    0,  383,  370,    0,  363,
      367,  384,  366,  364,  357,  372,  370,    0,  374,    0,
      359,  367,  371,  367,    0,  356,  369,    0,    0,  346,
      317,  313,  311,  328,  323,  310,  325,    0,    0,    0,
        0,    0,  313,  300,  298,  309,  301,  298,  290,  271,
      275,  282,  281,    0,    0,  264,    0,    0,  231,  217,
        0,  782,  357,  362,  367,  371,  374,  377,  382,  385,
      388,  239,  391,  187,  156,  117,   76,   49
    } ;

static yyconst flex_int16_t yy_def[579] =
    {   0,
      562,    1,  563,  563,  562,  562,  562,  562,  564,  565,
      566,  566,  562,  567,  566,  568,   15,   15,   15,   15,
       15,   15,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      562,  569,  562,  564,  562,  562,  565,  562,  566,  566,
       13,  567,   15,  566,   15,  566,  567,  562,  568,  570,
       15,  566,  566,  566,   15,  566,  566,   15,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  566,  566,  566,  566,  562,  569,  562,  562,
       50,  571,   58,  562,   58,  570,  562,   15,  566,  566,
      566,   15,  566,  566,   15,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  562,  566,  571,  572,  114,
      114,  114,  573,  117,  562,  117,  562,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  167,  572,  573,  574,
      175,  175,  175,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  575,  574,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  282,
      575,  576,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  577,
      576,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  577,  578,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  578,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,

      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,  566,  566,  566,  566,  566,  566,  566,  566,  566,
      566,    0,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562
    } ;

static yyconst flex_int16_t yy_nxt[832] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   14,    8,   15,   12,
       12,   16,    6,   12,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   12,   40,   41,
       41,  433,   42,   41,   41,   80,   42,   43,   43,   45,
       81,   46,   49,   50,   51,   51,   51,   51,   51,   51,
       51,   51,   52,   83,   53,   54,   49,   84,  403,   49,
       53,   53,   53,   55,   53,   53,   49,   56,   49,   54,
       49,   56,   49,   49,   49,   49,   49,   56,   49,   49,

       49,   49,   49,   49,   49,   53,   53,   53,   53,   53,
       53,   53,   53,   52,   66,   53,   74,   67,   75,  371,
       61,   53,   53,   53,   53,   53,   53,   62,   68,   63,
       76,   85,   69,   90,   64,   87,   70,   91,   86,   77,
       88,   93,   98,  103,   99,   94,  101,  100,  134,   78,
      102,  135,   92,  107,  107,   95,  104,  109,  331,  110,
       96,   43,   43,   45,  136,   46,  111,  111,  111,  111,
      111,  111,  111,  111,  113,  113,  113,  113,  113,  113,
      113,  113,  114,  150,  115,  109,  153,  110,  151,  284,
      115,  115,  115,  115,  115,  115,  154,  107,  107,  170,

      170,  170,  170,  170,  170,  170,  170,  171,  193,  172,
      256,  347,  348,  257,  194,  172,  172,  172,  172,  172,
      172,  115,  115,  115,  115,  115,  115,  115,  115,  174,
      174,  174,  174,  174,  174,  174,  174,  175,  253,  176,
      210,  228,  213,  177,  280,  176,  176,  176,  176,  176,
      176,  214,  211,  216,  254,  255,  281,  439,  561,  560,
      440,  217,  227,  227,  227,  227,  227,  227,  227,  227,
      172,  172,  172,  172,  172,  172,  172,  172,  231,  231,
      231,  231,  231,  231,  231,  231,  232,  293,  233,  515,
      559,  516,  177,  294,  233,  233,  233,  233,  233,  233,

      176,  176,  176,  176,  176,  176,  176,  176,  278,  558,
      557,  556,  555,  279,  233,  233,  233,  233,  233,  233,
      233,  233,  330,  330,  330,  330,  330,  330,  330,  330,
      376,  390,  554,  553,  552,  377,  391,  551,  550,  392,
      549,  393,  410,  411,  412,  548,  413,  446,  447,  547,
      546,  545,  544,  543,  542,  541,  448,    6,    6,    6,
        6,    6,   44,   44,   44,   44,   44,   47,   47,   47,
       47,   47,   49,   49,  540,   49,   57,   57,   57,   59,
       59,   59,  108,  108,  108,  108,  108,  116,  116,  116,
      168,  168,  168,  229,  229,  229,  539,  538,  537,  536,

      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  521,  520,  519,  518,  517,  514,
      513,  512,  511,  510,  509,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  499,  498,  497,  496,  495,  494,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  461,  460,  177,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  445,  444,  443,  442,
      441,  438,  437,  436,  435,  434,  432,  431,  430,  429,

      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  400,  409,  408,  407,  406,
      405,  404,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  375,  374,  373,  372,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,

      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  292,
      291,  290,  289,  288,  287,  286,  285,  230,  175,  283,
      282,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      230,  175,  169,  114,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  215,  212,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,

      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  173,  169,  114,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  152,  149,  148,  147,  146,  145,  144,   86,  143,
      142,  141,  140,  139,  138,  137,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  118,  117,   60,  112,   58,   48,  106,  105,   97,
       89,   82,   79,   73,   72,   71,   65,   60,   58,   48,
      562,    5,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562
    } ;

static yyconst flex_int16_t yy_chk[832] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,  578,    3,    4,    4,   27,    4,    7,    7,    9,
       27,    9,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   29,   13,   13,   13,   29,  577,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   19,   15,   24,   19,   24,  576,
       17,   15,   15,   15,   15,   15,   15,   17,   20,   17,
       25,   30,   20,   33,   17,   31,   20,   33,   30,   25,
       31,   34,   36,   38,   36,   34,   37,   36,   77,   25,
       37,   77,   33,   41,   41,   34,   38,   42,  575,   42,
       34,   43,   43,   44,   77,   44,   50,   50,   50,   50,
       50,   50,   50,   50,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   93,   58,  108,   95,  108,   93,  574,
       58,   58,   58,   58,   58,   58,   95,  107,  107,  114,

      114,  114,  114,  114,  114,  114,  114,  114,  134,  114,
      201,  300,  300,  201,  134,  114,  114,  114,  114,  114,
      114,  115,  115,  115,  115,  115,  115,  115,  115,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  200,  117,
      151,  572,  153,  117,  226,  117,  117,  117,  117,  117,
      117,  153,  151,  155,  200,  200,  226,  411,  560,  559,
      411,  155,  167,  167,  167,  167,  167,  167,  167,  167,
      172,  172,  172,  172,  172,  172,  172,  172,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  245,  175,  498,
      556,  498,  175,  245,  175,  175,  175,  175,  175,  175,

      176,  176,  176,  176,  176,  176,  176,  176,  225,  553,
      552,  551,  550,  225,  233,  233,  233,  233,  233,  233,
      233,  233,  282,  282,  282,  282,  282,  282,  282,  282,
      339,  353,  549,  548,  547,  339,  353,  546,  545,  353,
      544,  353,  379,  379,  379,  543,  379,  418,  418,  537,
      536,  535,  534,  533,  532,  531,  418,  563,  563,  563,
      563,  563,  564,  564,  564,  564,  564,  565,  565,  565,
      565,  565,  566,  566,  530,  566,  567,  567,  567,  568,
      568,  568,  569,  569,  569,  569,  569,  570,  570,  570,
      571,  571,  571,  573,  573,  573,  527,  526,  524,  523,

      522,  521,  519,  517,  516,  515,  514,  513,  512,  511,
      510,  508,  507,  504,  503,  502,  501,  500,  499,  496,
      495,  494,  493,  492,  491,  490,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  464,  463,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  450,  449,
      448,  447,  446,  445,  444,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  429,  428,  427,  426,
      425,  424,  423,  422,  420,  419,  416,  415,  414,  413,
      412,  409,  408,  407,  406,  405,  402,  401,  399,  398,

      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  377,  376,  375,  373,
      372,  371,  369,  364,  363,  362,  360,  359,  358,  356,
      355,  352,  351,  350,  349,  348,  347,  346,  345,  343,
      342,  341,  340,  338,  337,  335,  334,  331,  329,  328,
      326,  325,  324,  323,  322,  321,  318,  315,  313,  312,
      310,  309,  308,  307,  306,  304,  303,  302,  301,  299,
      298,  297,  296,  295,  294,  293,  291,  290,  289,  288,
      287,  286,  285,  284,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,

      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  244,
      242,  241,  239,  238,  237,  236,  234,  231,  229,  228,
      227,  224,  223,  222,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      203,  199,  197,  196,  194,  193,  192,  191,  190,  189,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      174,  173,  170,  168,  165,  164,  163,  162,  160,  159,
      158,  157,  156,  154,  152,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  139,  138,  137,  136,  135,

      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  119,  118,  116,  113,  112,  111,  110,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   94,   92,   91,   90,   89,   88,   87,   85,   84,
       83,   82,   81,   80,   79,   78,   76,   75,   74,   73,
       72,   71,   70,   69,   68,   67,   66,   65,   64,   63,
       62,   61,   60,   59,   57,   52,   47,   40,   39,   35,
       32,   28,   26,   23,   22,   21,   18,   16,   14,   10,
        5,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[92] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "cf-lex.l"
/*  Copyright (C) 2011 CZ.NIC, z.s.p.o. <knot-dns@labs.nic.cz>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#line 17 "cf-lex.l"

#include <arpa/inet.h>
#include <config.h>
#include <dirent.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "utils/knot1to2/scheme.h"
#include "utils/knot1to2/includes.h"
#include "utils/knot1to2/extra.h"
#include "utils/knot1to2/cf-parse.tab.h"
#include "contrib/openbsd/strlcpy.h"

/* Imported symbols. */
#define lval (yylval->tok)
extern void cf_error(void *scanner, const char *format, ...);

/* Convert hex to binary. */
static inline char xd(char d) {
	if (d >= '0' && d <= '9') return d - '0';
	if (d >= 'a' && d <= 'f') return d - 'a' + 10;
	if (d >= 'A' && d <= 'F') return d - 'A' + 10;
	return 0;
}
int hex2bin(const char* src, char *dst, size_t len) {
	for (unsigned i = 0; i < len; ++i) {
		dst[i] = (xd(src[i<<1])<<4) + xd(src[(i<<1)+1]);
	}
	return 0;
}

#define YY_NO_UNPUT

#define YY_NO_INPUT 1

#line 888 "cf-lex.c"

#define INITIAL 0
#define include 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE conf_extra_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int cf_lex_init (yyscan_t* scanner);

int cf_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cf_lex_destroy (yyscan_t yyscanner );

int cf_get_debug (yyscan_t yyscanner );

void cf_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE cf_get_extra (yyscan_t yyscanner );

void cf_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *cf_get_in (yyscan_t yyscanner );

void cf_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *cf_get_out (yyscan_t yyscanner );

void cf_set_out  (FILE * out_str ,yyscan_t yyscanner );

int cf_get_leng (yyscan_t yyscanner );

char *cf_get_text (yyscan_t yyscanner );

int cf_get_lineno (yyscan_t yyscanner );

void cf_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * cf_get_lval (yyscan_t yyscanner );

void cf_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cf_wrap (yyscan_t yyscanner );
#else
extern int cf_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cf_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int cf_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 74 "cf-lex.l"

#line 1125 "cf-lex.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cf_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		cf__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 563 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 782 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 75 "cf-lex.l"
/* Ignore comments */;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 76 "cf-lex.l"
/* Ignore whitespace */;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "cf-lex.l"
{ return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "cf-lex.l"
{ lval.t = yytext; return SYSTEM; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "cf-lex.l"
{ lval.t = yytext; return IDENTITY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "cf-lex.l"
{ lval.t = yytext; return HOSTNAME; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "cf-lex.l"
{ lval.t = yytext; return SVERSION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "cf-lex.l"
{ lval.t = yytext; return NSID; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "cf-lex.l"
{ lval.t = yytext; return MAX_UDP_PAYLOAD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "cf-lex.l"
{ lval.t = yytext; return STORAGE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "cf-lex.l"
{ lval.t = yytext; return KEY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "cf-lex.l"
{ lval.t = yytext; return KEYS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "cf-lex.l"
{ lval.t = yytext; return REMOTES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "cf-lex.l"
{ lval.t = yytext; return GROUPS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "cf-lex.l"
{ lval.t = yytext; return ZONES; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "cf-lex.l"
{ lval.t = yytext; return FILENAME; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "cf-lex.l"
{ lval.t = yytext; return DISABLE_ANY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "cf-lex.l"
{ lval.t = yytext; return SEMANTIC_CHECKS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_RETRIES; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_TIMEOUT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "cf-lex.l"
{ lval.t = yytext; return DBSYNC_TIMEOUT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "cf-lex.l"
{ lval.t = yytext; return IXFR_FSLIMIT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "cf-lex.l"
{ lval.t = yytext; return XFR_IN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "cf-lex.l"
{ lval.t = yytext; return XFR_OUT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "cf-lex.l"
{ lval.t = yytext; return UPDATE_IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_IN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_OUT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "cf-lex.l"
{ lval.t = yytext; return WORKERS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "cf-lex.l"
{ lval.t = yytext; return BACKGROUND_WORKERS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "cf-lex.l"
{ lval.t = yytext; return ASYNC_START; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "cf-lex.l"
{ lval.t = yytext; return USER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "cf-lex.l"
{ lval.t = yytext; return PIDFILE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "cf-lex.l"
{ lval.t = yytext; return RUNDIR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "cf-lex.l"
{ lval.t = yytext; return BUILD_DIFFS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "cf-lex.l"
{ lval.t = yytext; return SERIAL_POLICY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_IDLE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 112 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_HS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 113 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_REPLY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "cf-lex.l"
{ lval.t = yytext; return MAX_TCP_CLIENTS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SIZE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SLIP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "cf-lex.l"
{ lval.t = yytext; return TRANSFERS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 119 "cf-lex.l"
{ lval.t = yytext; return DNSSEC_ENABLE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 120 "cf-lex.l"
{ lval.t = yytext; return DNSSEC_KEYDIR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "cf-lex.l"
{ lval.t = yytext; return SIGNATURE_LIFETIME; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "cf-lex.l"
{ lval.t = yytext; return QUERY_MODULE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 124 "cf-lex.l"
{ lval.t = yytext; return INTERFACES; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 125 "cf-lex.l"
{ lval.t = yytext; return ADDRESS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 126 "cf-lex.l"
{ lval.t = yytext; return PORT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 127 "cf-lex.l"
{ lval.t = yytext; return VIA; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "cf-lex.l"
{ lval.t = yytext; return CONTROL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "cf-lex.l"
{ lval.t = yytext; return ALLOW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "cf-lex.l"
{ lval.t = yytext; return LISTEN_ON; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "cf-lex.l"
{ lval.t = yytext; return LOG; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "cf-lex.l"
{ lval.t = C_ANY;  return LOG_SRC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "cf-lex.l"
{ lval.t = C_SRV;  return LOG_SRC; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "cf-lex.l"
{ lval.t = C_ZONE; return LOG_SRC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 139 "cf-lex.l"
{ lval.t = yytext; return LOG_DEST; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 140 "cf-lex.l"
{ lval.t = yytext; return LOG_DEST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 141 "cf-lex.l"
{ lval.t = yytext; return LOG_DEST; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 143 "cf-lex.l"
{ lval.t = "debug";    return LOG_LEVEL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 144 "cf-lex.l"
{ lval.t = "info";     return LOG_LEVEL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 145 "cf-lex.l"
{ lval.t = "notice";   return LOG_LEVEL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 146 "cf-lex.l"
{ lval.t = "warning";  return LOG_LEVEL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 147 "cf-lex.l"
{ lval.t = "error";    return LOG_LEVEL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 148 "cf-lex.l"
{ lval.t = "critical"; return LOG_LEVEL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 149 "cf-lex.l"
{ lval.t = "info";     return LOG_LEVEL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 151 "cf-lex.l"
{
  if (strcmp(yytext, "increment") == 0) {
    lval.t = "increment";
  } else {
    lval.t = "unixtime";
  }
  return SERIAL_POLICY_VAL;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "cf-lex.l"
{
  lval.t = yytext;
  lval.i = 0;
  if (strcmp(yytext, "on") == 0) {
    lval.i = 1;
  }
  return BOOL;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "cf-lex.l"
BEGIN(include);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atoi(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "interval must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'm': lval.i *= 60; break; /* minutes */
  case 'h': lval.i *= 60*60; break; /* hours */
  case 'd': lval.i *= 24*60*60; break; /* days */
  case 's': /* seconds */
  default: break;
  }

  return INTERVAL;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atol(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "size must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'k': lval.l = lval.i * 1024; break; /* kB */
  case 'M': lval.l = lval.i * 1024*1024; break; /* MB */
  case 'G': lval.l = lval.i * 1024*1024*1024; break; /* GB */
  default: break;
  }

  return SIZE;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 214 "cf-lex.l"
{
  lval.i = atol(yytext);
  return NUM;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 219 "cf-lex.l"
{
  unsigned char buf[sizeof(struct in_addr)];
  if (inet_pton(AF_INET, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA;
  }
  cf_error(yyscanner, "Invalid IP address.");
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 228 "cf-lex.l"
{
  unsigned char buf[sizeof(struct in6_addr)];
  yytext[strlen(yytext)-1] = '\0';
  if (inet_pton(AF_INET6, yytext+1, buf)) {
	  lval.t = strdup(yytext+1);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
  }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 238 "cf-lex.l"
{
  unsigned char buf[sizeof(struct in6_addr)];
  if (inet_pton(AF_INET6, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 247 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 248 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 249 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 250 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 251 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 252 "cf-lex.l"
{ lval.t = strdup(yytext); return TSIG_ALGO_NAME; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 254 "cf-lex.l"
{
  yytext[yyleng-1] = 0;
  lval.t = strdup(yytext + 1);
  return TEXT;
}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 260 "cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 262 "cf-lex.l"
{
  lval.t = strdup(yytext);
  return TEXT /* Last resort, alphanumeric word. */;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 267 "cf-lex.l"
/* Optional : in assignments. */;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include):
#line 269 "cf-lex.l"
{
	conf_includes_remove(yyextra->includes);

	cf_pop_buffer_state(yyscanner);

	if (!YY_CURRENT_BUFFER) {
		return END;
	}
}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 279 "cf-lex.l"

	YY_BREAK
case 89:
YY_RULE_SETUP
#line 280 "cf-lex.l"
{
	BEGIN(INITIAL);

	// silently skip includes if there was a former error
	if (yyextra->error) {
		return END;
	}

	// remove optional semicolon
	if (yytext[yyleng - 1] == ';') {
		yyleng -= 1;
	}
	// remove quotes
	yytext += 1;
	yyleng -= 2;
	yytext[yyleng] = '\0';

	if (!conf_includes_push(yyextra->includes, yytext)) {
		cf_error(yyscanner, "include loop");
		return END;
	}

	// retrieved relative to previous config
	conf_include_t *inc = conf_includes_top(yyextra->includes);

	FILE *included = fopen(inc->filename, "r");
	if (!included) {
		cf_error(yyscanner, "cannot open file '%s'", inc->filename);
		conf_includes_remove(yyextra->includes);
		return END;
	}
	inc->handle = included;

	struct stat file_stat;
	if (fstat(fileno(included), &file_stat) == -1) {
		cf_error(yyscanner, "cannot stat file '%s'", yytext);
		conf_includes_remove(yyextra->includes);
		return END;
	}

	if (S_ISDIR(file_stat.st_mode)) {
		// Store dirname statically to reduce deallocation.
		char dirname[256] = { 0 };
		int ret = snprintf(dirname, sizeof(dirname), "%s",
		                   inc->filename);
		if (ret <= 0 || ret >= sizeof(dirname)) {
			cf_error(yyscanner, "dir name is too long '%s'",
			         inc->filename);
			return END;
		}

		// Remove include directory from the stack.
		conf_includes_remove(yyextra->includes);

		DIR *dp = opendir(dirname);
		if (dp == NULL) {
			cf_error(yyscanner, "cannot open directory '%s'",
			         dirname);
			return END;
		}

		struct dirent *ep;
		while ((ep = readdir(dp)) != NULL) {
			// Skip names with leading dot.
			if (*ep->d_name == '.') {
				continue;
			}

			char infile[256] = { 0 };
			int ret = snprintf(infile, sizeof(infile), "%s/%s",
			                   dirname, ep->d_name);
			if (ret <= 0 || ret >= sizeof(infile)) {
				cf_error(yyscanner, "cannot open file '%s/%s'",
				         dirname, ep->d_name);
				return END;
			}

			if (!conf_includes_push(yyextra->includes, infile)) {
				cf_error(yyscanner, "include loop");
				return END;
			}

			// retrieved relative to previous config
			conf_include_t *inc = conf_includes_top(yyextra->includes);

			FILE *included = fopen(inc->filename, "r");
			if (!included) {
				cf_error(yyscanner, "cannot open file '%s'",
				         inc->filename);
				conf_includes_remove(yyextra->includes);
				return END;
			}
			inc->handle = included;

			YY_BUFFER_STATE bs = cf__create_buffer(included,YY_BUF_SIZE,yyscanner);
			cf_push_buffer_state(bs,yyscanner);
		}
		(void)closedir(dp);
	} else {
		YY_BUFFER_STATE bs = cf__create_buffer(included,YY_BUF_SIZE,yyscanner);
		cf_push_buffer_state(bs,yyscanner);
	}
}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 386 "cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 388 "cf-lex.l"
ECHO;
	YY_BREAK
#line 1882 "cf-lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * cf_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( cf_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cf_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cf_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cf_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cf_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 563 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 563 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 562);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cf_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cf_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cf_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        cf_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	cf__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	cf__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void cf__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cf_pop_buffer_state();
	 *		cf_push_buffer_state(new_buffer);
     */
	cf_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cf__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (cf_wrap()) processing, but the only time this flag
	 * is looked at is after cf_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void cf__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cf__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cf_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cf__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cf__create_buffer()
 * @param yyscanner The scanner object.
 */
    void cf__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cf_free((void *) b->yy_ch_buf ,yyscanner );

	cf_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cf_restart() or at EOF.
 */
    static void cf__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	cf__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cf__init_buffer was _probably_
     * called from cf_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void cf__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cf__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	cf_ensure_buffer_stack(yyscanner);

	/* This block is copied from cf__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cf__switch_to_buffer. */
	cf__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void cf_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		cf__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cf_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cf__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cf__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cf_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cf__scan_bytes() instead.
 */
YY_BUFFER_STATE cf__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return cf__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to cf_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cf__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cf_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cf__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cf__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE cf_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int cf_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int cf_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int cf_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *cf_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void cf_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cf_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cf_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see cf__switch_to_buffer
 */
void cf_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void cf_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int cf_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void cf_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * cf_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void cf_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* cf_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int cf_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* cf_lex_init_extra has the same functionality as cf_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to cf_alloc in
 * the yyextra field.
 */

int cf_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    cf_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    cf_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cf_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cf_lex_init()
     */
    return 0;
}

/* cf_lex_destroy is for both reentrant and non-reentrant scanners. */
int cf_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cf_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	cf_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        cf_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cf_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    cf_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cf_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *cf_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cf_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see cf_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 388 "cf-lex.l"



