.TH knotc "8" "November 2011" "CZ.NIC Labs" "Knot DNS, version 0.8"
.SH NAME
.B knot
\- Knot DNS control utility
.SH SYNOPSIS
.B knotc
[\fIparameters\fR] \fIstart|stop|restart|reload|running|compile\fR
.SH DESCRIPTION
.SS "Parameters:"
.HP
\fB\-c\fR [file], \fB\-\-config\fR=\fI[file]\fR Select configuration file.
.TP
\fB\-j\fR [num], \fB\-\-jobs\fR=\fI[num]\fR
Number of parallel tasks to run (only for 'compile').
.TP
\fB\-f\fR, \fB\-\-force\fR
Force operation \- override some checks.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose mode \- additional runtime information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print knot server version.
.TP
\fB\-w\fR, \fB\-\-wait\fR
Wait for the server to finish start/stop operations.
.TP
\fB\-i\fR, \fB\-\-interactive\fR
Interactive mode (do not daemonize).
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help and usage.
.SS "Actions:"
.TP
start
Start knot server zone (no\-op if running).
.TP
stop
Stop knot server (no\-op if not running).
.TP
restart
Stops and then starts knot server.
.TP
reload
Reload knot configuration and compiled zones.
.TP
running
check if server is running.
.TP
compile
Compile zone file.
.SH "SEE ALSO"
The full documentation for
.B Knot
is maintained as a Texinfo manual.  If the
.B info
and
.B Knot
programs are properly installed at your site, the command
.IP
.B info Knot
.PP
should give you access to the complete manual.
