.TH "knsupdate" "8" "April 2013" "CZ.NIC Labs" "Knot DNS, version 1.2.0-rc3"
.SH NAME
.B knsupdate
\- Dynamic DNS update utility based on libknot
.SH SYNOPSIS
.B knsupdate
[\fIoptions\fR]
.SH DESCRIPTION
.TP 4
\fI x\fR
x
.SH OPTIONS
.TP 4
.BI -4
Use IPv4 protocol only.
.SH FILES
.BI /etc/resolv.conf
.SH SEE ALSO
.BI khost\fR(8),
.BI kdig\fR(8).
