FROM ubuntu:latest
LABEL maintainer="Knot DNS <knot-dns@labs.nic.cz>"
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install \
	autoconf \
	automake \
	autotools-dev \
	build-essential \
	curl \
	ghostscript \
	git \
	language-pack-en \
	latexmk \
	libbpf-dev \
	libedit-dev \
	libfstrm-dev \
	libgnutls28-dev \
	libidn2-dev \
	liblmdb-dev \
	libmaxminddb-dev \
	libmnl-dev \
	libnghttp2-dev \
	libprotobuf-c-dev \
	libsystemd-dev \
	libtool \
	liburcu-dev \
	libxdp-dev \
	pkg-config \
	protobuf-c-compiler \
	python3-sphinx \
	texlive \
	texlive-font-utils \
	texlive-latex-extra \
	unzip
